apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${{ values.serviceName }}
  namespace: staging
  labels:
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  schedule: '${{ values.schedule }}'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            backstage.io/kubernetes-id: ${{ values.serviceName }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: worker
              image: docker.io/library/busybox@sha256:bdf57e528e45e4433820e045b29b4597825a1c9e38353532d90a01445013f82e
              imagePullPolicy: IfNotPresent
              command: [sh, -c, 'echo scheduled demo task completed']
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
