apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceName }}
  namespace: staging
  labels:
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${{ values.serviceName }}
  ports:
    - name: http
      port: 80
      targetPort: http
