import { basename } from 'node:path';
import {
  cloudRuntimeSnapshotHasIntegrity,
  createCloudRuntimeSnapshot,
  revalidateCloudRuntimeSnapshot,
} from './cloudRuntimeSnapshot';
import { cloudDeliveryFixture } from './testFixtures/cloudDeliveryFixture';
import { canonicalize, sha256 } from './snapshot';
import { JevClient } from './jev';
import { cloudSnapshotHasIntegrity } from './cloudSnapshot';

function fixture() {
  const release = cloudDeliveryFixture().snapshot;
  const target = release.envelope.target;
  const contents = Object.fromEntries(
    release.files.map(file => [basename(file.path), file.content]),
  );
  const backend = JSON.parse(contents['backend-deployment.yaml']);
  backend.spec.replicas = 1;
  contents['backend-deployment.yaml'] = `${canonicalize(backend)}\n`;
  const gitopsBase = {
    revision: 'b'.repeat(40),
    files: Object.keys(contents).map(name => ({
      name,
      sha256: sha256(contents[name]),
    })),
  };
  const context = {
    proposalId: '00000000-0000-4000-8000-000000000099',
    requester: 'user:default/developer',
    submissionChannel: 'mcp_action' as const,
  };
  const input = {
    operation: 'runtime_change',
    declaredIntent:
      'Increase only the Rizz.AI backend to two replicas; leave frontend, images and model unchanged.',
    targetId: 'eks-staging',
    patch: { backendReplicas: 2 },
  };
  return { input, context, target, gitopsBase, contents };
}

it('freezes a separate versioned operation, exact files and provenance', () => {
  const snapshot = createCloudRuntimeSnapshot(fixture());
  expect(snapshot.envelope).toMatchObject({
    schemaVersion: 2,
    kind: 'rizz_cloud_runtime_change',
    intentSource: 'agent_supplied',
    policyVersion: 'rizz-app-v2-distinct-app-or-platform-review',
    reviewerGroups: ['group:default/rizz-team', 'group:default/platform-team'],
    changedFields: ['backendReplicas'],
    before: { frontendReplicas: 1, backendReplicas: 1 },
    after: { frontendReplicas: 1, backendReplicas: 2 },
  });
  expect(snapshot.files).toHaveLength(9);
  expect(snapshot.baselineFiles).toHaveLength(9);
  expect(cloudRuntimeSnapshotHasIntegrity(snapshot)).toBe(true);
  expect(cloudSnapshotHasIntegrity(snapshot)).toBe(false);
  expect(
    cloudRuntimeSnapshotHasIntegrity(cloudDeliveryFixture().snapshot),
  ).toBe(false);
  const rest = createCloudRuntimeSnapshot({
    ...fixture(),
    context: { ...fixture().context, submissionChannel: 'backstage_rest' },
  });
  expect(rest.envelope.intentSource).toBe('authenticated_user_submitted');
  expect(rest.digest).not.toBe(snapshot.digest);
});

it('detects modified intent, patch, target, baseline and generated bytes', () => {
  const snapshot = createCloudRuntimeSnapshot(fixture());
  for (const tamper of [
    (value: any) => {
      value.envelope.declaredIntent = 'Scale everything';
    },
    (value: any) => {
      value.envelope.patch.backendReplicas = 1;
    },
    (value: any) => {
      value.envelope.target.namespace = 'default';
    },
    (value: any) => {
      value.envelope.gitopsBase.revision = 'a'.repeat(40);
    },
    (value: any) => {
      value.baselineFiles[0].content += ' ';
    },
    (value: any) => {
      value.files[0].content += ' ';
    },
    (value: any) => {
      value.envelope.changedFields = ['frontendReplicas'];
    },
    (value: any) => {
      value.envelope.reviewerGroups = ['group:default/platform-team'];
    },
  ]) {
    const changed = structuredClone(snapshot);
    tamper(changed);
    expect(cloudRuntimeSnapshotHasIntegrity(changed)).toBe(false);
  }
});

it('preserves the old platform-only runtime contract without widening approval', () => {
  const legacy = createCloudRuntimeSnapshot({
    ...fixture(),
    policyVersion: 'rizz-runtime-v1-distinct-platform-review',
  });
  expect(legacy.envelope.reviewerGroups).toBeUndefined();
  expect(cloudRuntimeSnapshotHasIntegrity(legacy)).toBe(true);
});

it('requires fresh matching target, base revision and exact baseline bytes', () => {
  const source = fixture();
  const snapshot = createCloudRuntimeSnapshot(source);
  expect(revalidateCloudRuntimeSnapshot(snapshot, source)).toEqual({
    valid: true,
  });
  expect(
    revalidateCloudRuntimeSnapshot(snapshot, {
      ...source,
      gitopsBase: { ...source.gitopsBase, revision: 'c'.repeat(40) },
    }),
  ).toEqual({ valid: false, reason: 'gitops_base_changed' });
  expect(
    revalidateCloudRuntimeSnapshot(snapshot, {
      ...source,
      target: {
        ...source.target,
        gitopsRepository: 'https://github.com/different/gitops.git',
      },
    }),
  ).toEqual({ valid: false, reason: 'target_changed' });
  expect(
    revalidateCloudRuntimeSnapshot(snapshot, {
      ...source,
      contents: {
        ...source.contents,
        'runtime.yaml': `${source.contents['runtime.yaml']} `,
      },
    }),
  ).toEqual({ valid: false, reason: 'runtime_baseline_changed' });
});

it('passes only compact semantic change context to Jev', async () => {
  const snapshot = createCloudRuntimeSnapshot(fixture());
  const fetcher = jest
    .fn()
    .mockResolvedValue(new Response(null, { status: 503 }));
  await new JevClient(
    'fixture-key-not-live',
    fetcher as typeof fetch,
  ).evaluateRuntimeChange(snapshot);
  const state = JSON.parse(fetcher.mock.calls[0][1].body).state;
  expect(state.operation).toBe('runtime_change');
  expect(state.changedFields).toEqual(['backendReplicas']);
  expect(state.before.backendReplicas).toBe(1);
  expect(state.after.backendReplicas).toBe(2);
  expect(state.preservedFields).toContain('image digests');
  expect(JSON.stringify(state)).not.toContain(
    snapshot.envelope.target.accountId,
  );
  expect(JSON.stringify(state)).not.toContain(
    snapshot.envelope.target.ingress.operatorCidr,
  );
  expect(JSON.stringify(state)).not.toContain(
    snapshot.envelope.target.ingress.certificateArn,
  );
  const altered = structuredClone(snapshot);
  altered.files[0].content += ' ';
  expect(
    await new JevClient(
      'fixture-key-not-live',
      fetcher as typeof fetch,
    ).evaluateRuntimeChange(altered),
  ).toEqual({
    kind: 'unavailable',
    reason: 'snapshot_integrity_failed',
  });
  expect(fetcher).toHaveBeenCalledTimes(1);
});
